from re import I


def arda():
    print ("arda är dum i huvudet")

def ham():
    print ("Hampus har lektion med te-21")
for _ in range (4):
    ham ()
    arda()

def hello_world():
    print ("Hampus",)



hello_world()
hello_world ()




def funktions_namn():
    # här är det funktionen gör
    print()

def namn():
    print ("jag heter Mohammed och jag studerar i den tekniska programmet")



def arda():
    print ("jag är turkburk")

for _ in range(6):
    namn()
    arda()

def mow ():
    print ("Mohammed är upptagen med sin lektion")

for _ in range (5):
    mow()
